spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/woniu_sys
    username: root
    password: root123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.woniuxy.cq.ssmboot39.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level:
    com.woniuxy.cq.ssmboot39: debug
    org:
      apache:
        shiro: debug
shiro:
  # 登录页面
  loginUrl: /login.html
  # 登录成功之后跳转的页面
  successUrl: /