package com.woniuxy.cq.ssmboot39.entity;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.birthday
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.status
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.reg_time
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    private Date regTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.university
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    private String university;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.major
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.university_graduate_time
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    private Date universityGraduateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_id
     *
     * @param studentId the value for student.student_id
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.birthday
     *
     * @return the value of student.birthday
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.birthday
     *
     * @param birthday the value for student.birthday
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.status
     *
     * @return the value of student.status
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.status
     *
     * @param status the value for student.status
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.reg_time
     *
     * @return the value of student.reg_time
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.reg_time
     *
     * @param regTime the value for student.reg_time
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.university
     *
     * @return the value of student.university
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public String getUniversity() {
        return university;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.university
     *
     * @param university the value for student.university
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public void setUniversity(String university) {
        this.university = university == null ? null : university.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.major
     *
     * @return the value of student.major
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.major
     *
     * @param major the value for student.major
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.university_graduate_time
     *
     * @return the value of student.university_graduate_time
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public Date getUniversityGraduateTime() {
        return universityGraduateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.university_graduate_time
     *
     * @param universityGraduateTime the value for student.university_graduate_time
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    public void setUniversityGraduateTime(Date universityGraduateTime) {
        this.universityGraduateTime = universityGraduateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Aug 24 14:32:06 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", studentId=").append(studentId);
        sb.append(", name=").append(name);
        sb.append(", birthday=").append(birthday);
        sb.append(", status=").append(status);
        sb.append(", regTime=").append(regTime);
        sb.append(", university=").append(university);
        sb.append(", major=").append(major);
        sb.append(", universityGraduateTime=").append(universityGraduateTime);
        sb.append("]");
        return sb.toString();
    }
}